### ISSUE TITLE
{ code: 4000, message: 'No Client ID Specified' }

### ISSUE THREAD

**Issue by NismoGraphics** [Vereas/photoshop-rich-presence#1]
Title -- Comes when starting up.

I'm currently making my own but just fyi.

**Comment by NismoGraphics** [comment]
Update: Doesn't work either.

**Comment by Vereas** [comment]
Fixed issue- Client ID was invalid, can also assure you that this works.

**Comment by NismoGraphics** [comment]
Still saying the same thing.

**Comment by NismoGraphics** [comment]
Of course.
